pycharm_project2/boardRoot/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noticeboard/', include('noticeboard.urls')),
]

pycharm_project2/boardRoot/noticeboard/urls.py
from django.urls import path
from . import views

app_name = 'noticeboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('write', views.write_article, name='write_article'),
    path('add', views.add_article, name='add_article'),
]

pycharm_project2/boardRoot/noticeboard/models.py
from django.db import models
from django.utils.timezone import now

class Notice(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    writeDate = models.DateTimeField(default=now, editable=False)
    writeID = models.CharField(max_length=50)

    def __str__(self):
        return self.title

# Create your models here.

pycharm_project2/boardRoot/noticeboard/views.py
from django.shortcuts import render
from noticeboard.models import Notice
# Create your views here.

def index(request):
    article_list = Notice.objects.all().order_by('-writeDate')
    context = { 'article_list': article_list }
    return render(request, 'noticeboard/index.html', context)

def write_article(request):
    return render(request, 'noticeboard/writeArticle.html')

pycharm_project2/boardRoot/templates/noticeboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>게시글 목록</title>
    <style>
        .cls1 {
            text-decoration: none;
        }
        .cls2 {
            text-align: center;
            font-size: 30px;
            display: block;
        }
    </style>
</head>
<body>
    <table align="center" border = "1" width="80%">
        <thead>
            <tr height="10", align="center" bgcolor="lightgreen">
                <th>글번호</th>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일</th>
            </tr>
        </thead>
        {%if article_list%}
        <tbody>
        {%for article in article_list %}
            <tr align="center">
                <td width="5%">{{forloop.counter}}</td>
                <td width="10%">{{article.writeID}}</td>
                <td align="left" width="35%">
                    <span style="padding-right:30px"></span>
                    <a class="cls1">{{article.title}}</a></td>
                <td width="10%">{{article.writeDate}}</td>
            </tr>
        {%endfor%}
        </tbody>
        {%else%}
        <tbody>
            <tr height="10">
                <td colspan="4">
                    <p align="center">
                        <b><span style="font-size: 15pt;"> 등록된 글이 없습니다. </span></b>

                    </p>
                </td>

            </tr>
        </tbody>
        {%endif%}
    </table>
    <a class="cls1" href="{% url 'noticeboard:write_article' %}">
        <span class="cls2">글쓰기</span>
    </a>
</body>
</html>

pycharm_project2/boardRoot/templates/noticeboard/writeArticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>새 글 작성</title>
</head>
<body>
  <h1 style="text-align:center"> 새글 쓰기 </h1>
  <form name="articleForm" method="post" action="{% url 'noticeboard:add_article' %}">
  {% csrf_token %}
    <table border="0" align="center" >
        <tbody>
          <tr>
              <td align="right" > 글제목:</td>
              <td colspan="2"><input type="text" size="63" maxlength="80" name="title"> </td>
          </tr>
          <tr>
              <td align="right" valign="top" ><br> 글내용:</td>
            <td colspan="2"><textarea name="content" rows="10" cols="65" maxlength="1800"></textarea></td>
          </tr>
          <tr>
              <td align="right" ></td>
              <td colspan="2">
                <input type="submit" value="글쓰기">
                <input type="button" value="목록보기" onclick="backToList(this.form)">
              </td>
          </tr>
        </tbody>
    </table>

  </form>
</body>
</html>